---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation script to create the orion-ptt-system in AWS'

Conditions:
  Route53: !Equals [!Ref CreateDNS, "true"]
  EnableVPC: !Equals [!Ref CreateVPC, "true"]
#  AutodetectAmiId: !Equals [ !Ref InstanceAmiId, "autodetect" ]

Parameters:
  ExistingVpcID:
    Description: ID of the VPC where the EC2 instances are to be launched. (Needed unless you enable VPC creation.)
    #Type: AWS::EC2::VPC::Id
    Type: String
    Default: ""

  ExistingPublicSubnet:
    Description: A public subnet where EC2 instances can be reached by the Internet. (Needed unless you enable VPC creation.)
    #Type: AWS::EC2::Subnet::Id
    Type: String
    Default: ""

  KeyName:
    Description: The EC2 Key Pair which will be used with all the EC2 instances launched as part of this cloudformation script.
    Type: AWS::EC2::KeyPair::KeyName

  AmiId:
    Description: AMI ID for your EC2 Instances.  Ubuntu Server 18.04 LTS is recommended.
    Type: AWS::EC2::Image::Id
#    Type: String
#    Default: "autodetect"

  InstanceType:
    Description: EC2 Instance type to launch.
    Default: m5.2xlarge
    Type: String

  VolumeSize:
    Description: Root Volume Size (in Gigabytes) for EC2 instances.
    Default: 50
    Type: String

  InstanceName:
    Description: Name for EC2 Node
    Default: orion-ptt-system
    Type: String

  CreateDNS:
    Description: Set to 'true' if you want to manage DNS via Route53
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  CreateDNSZoneID:
    Description: "Route53 Zone ID (Optional.  Required if creating DNS Records.)"
    Type: String
    Default: ""

  CreateDNSDomain:
    Description: "Domain for DNS Records (Optional  Required if creating DNS Records.)"
    Type: String
    Default: ""

  CreateVPC:
    Description: "Create a VPC."
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  CreateVPCName:
    Description: "Name of your new VPC. (Only needed if creating a VPC.)"
    Type: String
    Default: Orion PTT System

  CreateVPCAvailabilityZone:
    Description: "Availability Zone for your VPC network.  (Only needed if creating a VPC.)"
    Type: String
    Default: us-east-1a

  CreateVPCSubnetCidrBlock:
    Description: "Network address block for your VPC Subnet.  (Only needed if creating a VPC.)"
    Type: String
    Default: 10.44.0.0/24


Resources:
#  DescribeImagesRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Action: sts:AssumeRole
#            Effect: Allow
#            Principal:
#              Service: lambda.amazonaws.com
#      ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
#      Policies:
#        - PolicyName: DescribeImages
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#              - Action: ec2:DescribeImages
#                Effect: Allow
#                Resource: "*"
#
#  GetLatestAMI:
#    Type: AWS::Lambda::Function
#    Condition: AutodetectAmiId
#    Properties:
#      Runtime: python3.6
#      Handler: index.handler
#      Role: !Sub ${DescribeImagesRole.Arn}
#      Timeout: 60
#      Code:
#        ZipFile: |
#          import boto3
#          import cfnresponse
#          import json
#          import traceback
#
#          def handler(event, context):
#            try:
#              response = boto3.client('ec2').describe_images(
#                  Owners=[event['ResourceProperties']['Owner']],
#                  Filters=[
#                    {'Name': 'name', 'Values': [event['ResourceProperties']['Name']]},
#                    {'Name': 'architecture', 'Values': [event['ResourceProperties']['Architecture']]},
#                    {'Name': 'root-device-type', 'Values': ['ebs']},
#                  ],
#              )
#
#              amis = sorted(response['Images'],
#                            key=lambda x: x['CreationDate'],
#                            reverse=True)
#              id = amis[0]['ImageId']
#
#              cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, id)
#            except:
#              traceback.print_last()
#              cfnresponse.send(event, context, cfnresponse.FAIL, {}, "ok")
##              cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, "No ami found")
#
#  InstanceAmi:
#    Type: Custom::FindAMI
#    Condition: AutodetectAmiId
#    DependsOn: GetLatestAMI
#    Properties:
#      ServiceToken: !Sub ${GetLatestAMI.Arn}
#      Owner: "099720109477"
##      Name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
#      Name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
#      Architecture: x86_64

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
#      ImageId: !If [ AutodetectAmiId, !Ref InstanceAmi, !Ref InstanceAmiId ]
      KeyName: !Ref KeyName

      IamInstanceProfile: !Ref KubernetesNodeInstanceProfile
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            curl https://kurl.sh/orion-ptt-system | sudo bash

      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2

      NetworkInterfaces:
        - AssociatePublicIpAddress: "True"
          DeleteOnTermination: "True"
          SubnetId: !If [EnableVPC, !Ref Subnet, !Ref ExistingPublicSubnet]
          DeviceIndex: 0
          GroupSet:
            - Ref: InstanceSecurityGroup

      Tags:
        - Key: OrionRole
          Value: Kubernetes Node

        - Key: Name
          Value: !Sub ${AWS::StackName}-${InstanceName}

  KubernetesNodeRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${AWS::StackName}-kubernetes-node
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  KubernetesNodePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub ${AWS::StackName}-KubernetesNodePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticloadbalancing:DescribeLoadBalancers"
            Resource: "*"
      Roles:
        - Ref: "KubernetesNodeRole"

  KubernetesNodeInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: !Sub ${AWS::StackName}-KubernetesNodeInstanceProfile
      Roles:
        - Ref: "KubernetesNodeRole"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for orion-ptt-system
      GroupName: !Sub ${AWS::StackName}-orion-default-security-group
      VpcId: !If [EnableVPC, !Ref OrionVPC, !Ref ExistingVpcID]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8800
          ToPort: 8800
          CidrIp: 0.0.0.0/0

      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName} Orion PTT System Default Security Group

  AlnilamRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub alnilam.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  AtlasRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub atlas.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  IcarusRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub icarus.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  ObserverRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub observer.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  RigelRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub rigel.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  RigelProxyRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub rigel.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  VaultRecord:
    Type: AWS::Route53::RecordSet
    Condition: Route53
    Properties:
      TTL: 300
      Name: !Sub vault.${CreateDNSDomain}
      Type: A
      HostedZoneId: !Ref CreateDNSZoneID
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

  # The VPC
  OrionVPC:
    Type: AWS::EC2::VPC
    Condition: EnableVPC
    Properties:
      CidrBlock: 10.44.0.0/21
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref CreateVPCName

  # Internet Gateway
  Gateway:
    Type: AWS::EC2::InternetGateway
    Condition: EnableVPC

  # Attach the Internet Gateway to the VPC
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: EnableVPC
    Properties:
      InternetGatewayId:
        Ref: Gateway
      VpcId:
        Ref: OrionVPC

  # Route Table
  RouteTable:
    Type: AWS::EC2::RouteTable
    Condition: EnableVPC
    Properties:
      VpcId:
        Ref: OrionVPC

  # Route
  Route:
    Type: AWS::EC2::Route
    Condition: EnableVPC
    Properties:
      RouteTableId:
        Ref: RouteTable
      GatewayId:
        Ref: Gateway
      DestinationCidrBlock: "0.0.0.0/0"

  # Subnet
  Subnet:
    Type: AWS::EC2::Subnet
    Condition: EnableVPC
    Properties:
      AvailabilityZone:
        Ref: CreateVPCAvailabilityZone
      CidrBlock:
        Ref: CreateVPCSubnetCidrBlock
      VpcId:
        Ref: OrionVPC
      MapPublicIpOnLaunch: true

  SubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: EnableVPC
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: Subnet

#  ElasticIP:
#    Type: AWS::EC2::EIP
#    Condition: EnableVPC
#    Properties:
#      Domain: vpc
#
#

# Elastic IP's
#  resource "aws_eip" "nat1" {
#    vpc = true
#  }
#
#  resource "aws_eip" "nat2" {
#    vpc = true
#  }

# NAT Gateways
#  resource "aws_nat_gateway" "public1" {
#    allocation_id = aws_eip.nat1.id
#    subnet_id = aws_subnet.public1.id
#  }

Outputs:
  K8sNodeInternalIpAddress:
    Description: Internal IP Address of Kubernetes Instance
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-K8sNodePrivateIpAddress

  K8sNodeExternalIpAddress:
    Description: External IP Address of Kubernetes Instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub ${AWS::StackName}-K8sNodePublicIpAddress

  AlnilamFQDN:
    Description: FQDN of Alnilam Service
    Value: !Ref AlnilamRecord

  AtlasFQDN:
    Description: FQDN of Alnilam Service
    Value: !Ref AtlasRecord

  IcarusFQDN:
    Description: FQDN of Icarus Service
    Value: !Ref IcarusRecord

  ObserverFQDN:
    Description: FQDN of Observer Service
    Value: !Ref ObserverRecord

  RigelFQDN:
    Description: FQDN of Rigel Service
    Value: !Ref RigelRecord

  RigelProxyFQDN:
    Description: FQDN of Rigel Proxy Service
    Value: !Ref RigelProxyRecord

  VaultFQDN:
    Description: FQDN of VaultService
    Value: !Ref VaultRecord
