version: 2

jobs:
  push-to-s3:
    environment:
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: orion-ptt-system
      FILE_NAME: orion-ptt-system.yaml
    docker:
      - image: orionlabs/docker-ci-build-image:2.0.15
    steps:
      - checkout
      - run:
          name: Push the config file to s3
          command: aws s3 cp ./${FILE_NAME} s3://${S3_BUCKET_NAME}/${FILE_NAME}
      - run:
          name: enable public read access on the file
          command: aws s3api put-object-acl --bucket ${S3_BUCKET_NAME} --key ${FILE_NAME} --acl public-read
  push-to-beta:
    environment:
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: orion-ptt-system-beta
      FILE_NAME: orion-ptt-system.yaml
    docker:
      - image: orionlabs/docker-ci-build-image:2.0.15
    steps:
      - checkout
      - run:
          name: Push the config file to s3
          command: aws s3 cp ./${FILE_NAME} s3://${S3_BUCKET_NAME}/${FILE_NAME}
      - run:
          name: enable public read access on the file
          command: aws s3api put-object-acl --bucket ${S3_BUCKET_NAME} --key ${FILE_NAME} --acl public-read
workflows:
  version: 2
  primary:
    jobs:
      - push-to-s3:
          filters:
            branches:
              only:
                - master
      - push-to-beta:
          filters:
            branches:
              only:
                - beta
                - /beta-.*/
