version: 2

jobs:
  push-to-s3:
    environment:
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: orion-ptt-system
      FILE_NAME: orion-ptt-system.yaml
    docker:
      - image: orionlabs/docker-ci-build-image:2.0.15
    steps:
      - run:
          name: Push the config file to s3
          command: aws s3 cp ${FILE_NAME} s3://${S3_BUCKET_NAME}/FILE_NAME

workflows:
  version: 2
  primary:
    jobs:
      - push-to-s3:
          filters:
            branches:
              only:
                - master        
